config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :products

  root 'static_pages#index'
  get 'static_pages/about'
  get 'static_pages/faqs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:img, :title, :description, :price, :category)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((User.count == 1) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 1
      flash.notice = "You don't have privilege to do that!"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def faqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% elsif alert %>
  <p id="alert"><%= alert %></p>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "PEAR", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% end %>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "FAQ", static_pages_faqs_path %></li>
      <li><%= link_to "Contact", "mailto:support@pear.com" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href= "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="products">
  <h1>SHOP</h1>
  <div class="row">
    <% @products.each do |product| %>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
          <div class="product">
            <div class="img"><%= link_to image_tag(product.img, width: '550', class:  "img-responsive center-block"), product %></div>
            <h2><%= link_to product.title, product %></h2>
            <small><strong>Price: <%= product.price %>$</strong></small>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="product">
    <div class="row">
      <div class="col-xs-12 cold-sm-12 col-md-12 col-lg-12">
        <div class="img"><%= image_tag(@product.img, width: '950', class:  "img-responsive center-block") %></div>
      </div>
      <div class="col-xs-12 cold-sm-12 col-md-12 col-lg-12">
        <div class="text">
          <h2><%= @product.title %></h2>
          <h4><%= @product.price %>$</h4>
          <p>
            <%= @product.description %>
          </p>



          <p>
            <strong>Category:</strong>
            <%= @product.category %>
          </p>
          <div class="cart">
            <h3>Add to cart</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_product_path(@product) %>
    <%= link_to 'Destroy', @product, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
    <%= link_to 'Back', products_path %>
</div>

app/views/static_pages/about.html.erb
<div class="container">
  <div class="about_wrapper">
    <div class="text">
      <h1>About us</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
      <%= link_to "Contact", "mailto:support@pear.com" %>
    </div>
  </div>
</div>

app/views/static_pages/faqs.html.erb
<div class="container">
  <div class="faqs_wrapper">
    <div class="text">
      <h1>FAQ</h1>
      <h5>- Lorem ipsum dolor sit amet consectetur adipisicing elit ?</h5>
      <p>Paleo health goth fap gastropub green juice, pabst dreamcatcher synth narwhal. Narwhal PBR&B shoreditch pork belly, tattooed seitan green juice jianbing vinyl heirloom etsy bitters kickstarter.</p>
      <h5>- Lorem ipsum dolor sit amet consectetur adipisicing elit ?</h5>
      <p>Paleo health goth fap gastropub green juice, pabst dreamcatcher synth narwhal. Narwhal PBR&B shoreditch pork belly, tattooed seitan green juice jianbing vinyl heirloom etsy bitters kickstarter.</p>
      <h5>- Lorem ipsum dolor sit amet consectetur adipisicing elit ?</h5>
      <p>Paleo health goth fap gastropub green juice, pabst dreamcatcher synth narwhal. Narwhal PBR&B shoreditch pork belly, tattooed seitan green juice jianbing vinyl heirloom etsy bitters kickstarter.</p>
      <h5>- Lorem ipsum dolor sit amet consectetur adipisicing elit ?</h5>
      <p>Paleo health goth fap gastropub green juice, pabst dreamcatcher synth narwhal. Narwhal PBR&B shoreditch pork belly, tattooed seitan green juice jianbing vinyl heirloom etsy bitters kickstarter.</p>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="heading col-md-12">
        <div class="text">
          <h1>Your local Apple experts</h1>
          <h3>Free worldwide shipping on all orders</h3>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="categories">
  <div class="laptop">
    <div class="text">
      <h1><%= link_to "Laptops", "#" %>  </h1>
    </div>

  </div>
  <div class="smartphone">
    <div class="text">
      <h1><%= link_to "Smartphones", "#" %>  </h1>
    </div>
  </div>
  <div class="tablet">
    <div class="text">
      <h1><%= link_to "Tablets", "#" %>  </h1>
    </div>
  </div>
</div>